apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # or whatever matches your cloud
  resources:
    requests:
      storage: 2Gi
