---
- name: Initialize Kubernetes Master
  hosts: k8s_master
  become: true
  vars:
    kubeadm_join_command: ""
  tasks:
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      shell: containerd config default | tee /etc/containerd/config.toml > /dev/null

    - name: Set SystemdCgroup = true in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd to apply changes
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Start and enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Wait for containerd socket to be ready
      wait_for:
        path: /var/run/containerd/containerd.sock
        state: present
        timeout: 10

    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ master_public_ip }} --control-plane-endpoint={{ master_public_ip }}
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Copy admin.conf to ubuntu user's .kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Generate kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command to a file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /home/ubuntu/kubeadm_join_command
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Apply Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      become_user: ubuntu
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
