name: Deploy Frontend to K8s

on:
  push:
    branches: [ deploy/frontend ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ deploy/frontend ]
    paths:
      - 'frontend/**'
  workflow_dispatch: {}  # Enables manual trigger via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t nidhip24/cas-frontend:${{ github.sha }} .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push nidhip24/cas-frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0'

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname gha-tailscale --accept-routes

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
        echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

    - name: Update deployment with image tag
      run: |
        export IMAGE_TAG=${{ github.sha }}
        sed -i "s|nidhip24/cas-frontend:.*|nidhip24/cas-frontend:$IMAGE_TAG|g" k8s/frontend-deployment.yaml

    - name: Deploy frontend
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
    
    - name: Verify Rollout
      run: |
        kubectl rollout status deployment/frontend-app
    
    - name: Bring down Tailscale
      if: always()
      run: |
        sudo tailscale logout

