name: Deploy Infrastructure

on:
  push:
    branches: [ deploy/infra ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ deploy/infra ]
    paths:
      - 'infra/**'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  id-token: write  # For OIDC authentication with AWS

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
      
      - name: Print tfvars file
        shell: bash
        run: |
          echo "${{ secrets.TF_VARS_CONTENT }}" | base64 -d > terraform.tfvars

      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Clean up tfvars
        if: always()
        run: rm -f terraform.tfvars
